# The following enables several GHC versions to be tested; often it's enough to
# test only against the last release in a major GHC version. Feel free to omit
# lines listings versions you don't need/want testing for.
language: c
env:
 - GHCVER=7.6.3
 - GHCVER=7.8.4
 - GHCVER=7.10.3
 - GHCVER=8.0.1

# Note: the distinction between `before_install` and `install` is not important.
before_install:
 - unset CC
install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install libglib2.0-dev
 - travis_retry sudo apt-get install cabal-install-1.24 ghc-$GHCVER-prof ghc-$GHCVER-dyn alex-3.1.4 happy-1.19.5
 - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/1.24/bin:/opt/alex/3.1.4/bin:/opt/happy/1.19.5/bin:$PATH
 - travis_retry cabal update

script:
 - travis_retry cabal install --run-tests -v -j1

notifications:
 email: true

branches:
    only:
          - master
          - develop

deploy:
  provider: hackage
  username: keera_studios_ci
  password:
    secure: PmllS5ILGWnFS3FJtKaKMGDSzSoucxtKW4fEwFDWAG9WBLsNBon+t0hbYBHYw9q8F8/+/QCzkKlqlKyICrVakxMy4CYeCO9xIJdTOUSxmoaSYrk1wuTCSZHfBG3jRqaY+rVSUS0GcYe8sNsXtJO4f1X3CUyLceoEDQSoEEbR5Juizn55kwJEhfLRHv3JNjyHPU0El0nO7XJkBzeY3zi3PO+sYskHgIXhB9OJE5YSwGBOpU9RTSgskv4dbijDdPaQi/qBmeaRIEabY3wFe+PFEfLfZsb2POMYUAoSAEQJ8XwdRhyOnvvEyETNcw1fRgaTvRaLEYNc4PIxJblSMLTfxsaFvHZ5tGlXXAnZ7bAVvTWRTT0hlFzki7I6tMVWTkvWlRTagcjO75KkQrdmX9sCgpYIWxsLmgTZ6b3c8BbtmfgoSooU/zEXmmD+j2VpoWG/rhRbFSbW0v2zSdiy8c+ui4xkB+gORh6aFeX4He+TgyH3EDVntBB1D4J0HEeuqGDr9plfJoiy6oY8HAMdyp7WqYzANBSLUSqvywXscZIhxBqvM8fPcStVkIrOREcEMjGbVdta8DHmJDxaIEwd7Z0K9mn3tcpomR9VR5LKL0plVFEKnBMg00N75cuYvxVe/4D/xx7vTL8R6hHx62VHTXQkJ+QF/2Tc3sVtknQfFWca4+o=
  on:
    branch: master
    condition: "$GHCVER = 8.0.1"
